# 🔬 Polarscope — X-ray your Polars DataFrames

**Polarscope** gives you deep, one-call inspection and cleaning for [Polars](https://pola.rs) DataFrames:

- **`ps.xray(df)`** — a full statistical X-ray of every column: distributions, missingness, outliers, data-quality flags, normality tests, inline histograms.
- **`ps.fix(df)`** — clean & optimize in one call: snake_case headers, trimmed strings, shrunk dtypes, and a report of what changed.
- **Plots** — correlation heatmaps, missing-value bars, distributions, categorical frequencies (plotly or altair).
- **Three bundled datasets** to play with: `titanic`, `diabetes`, and `cardio` (70,000 rows).

```
pip install polarscope            # core
pip install "polarscope[all]"     # + plotly, altair, scipy extras
```

In [1]:
# !pip install "polarscope[all]"   # uncomment on Kaggle/Colab

import polars as pl
import polarscope as ps

print("polars", pl.__version__, "| polarscope", ps.__version__)

polars 1.42.0 | polarscope 1.9.0

---
## 1 | Built-in datasets

Three datasets ship inside the package — no downloads, no paths:

| Loader | Rows × Cols | Contents |
|---|---|---|
| `ps.titanic()` | 156 × 12 | Mixed types, missing values — great for cleaning demos |
| `ps.diabetes()` | 768 × 9 | All numeric — great for statistics and correlations |
| `ps.cardio()` | 70,000 × 13 | Large all-numeric health records — great for performance |

In [2]:
df_titanic = ps.titanic()
df_diabetes = ps.diabetes()
df_cardio = ps.cardio()

for name, d in [("titanic", df_titanic), ("diabetes", df_diabetes), ("cardio", df_cardio)]:
    print(f"{name:9s} {d.shape}")

titanic   (156, 12)
diabetes  (768, 9)
cardio    (70000, 13)

---
## 2 | `ps.xray()` — the core inspection function

The default call analyzes **numeric columns** and returns a formatted
[Great Tables](https://posit-dev.github.io/great-tables/) view with essential statistics
and an inline distribution histogram per column.

In [3]:
ps.xray(df_diabetes)

GT(_tbl_data=shape: (9, 16)
┌─────────────┬─────────┬───────┬────────────┬───┬─────────────┬────────────┬────────┬─────────────┐
│ Column      ┆ Dtype   ┆ Count ┆ null_count ┆ … ┆ Pct_Missing ┆ N_Outliers ┆ skew   ┆ Distributio │
│ ---         ┆ ---     ┆ ---   ┆ ---        ┆   ┆ ---         ┆ ---        ┆ ---    ┆ n_Plot      │
│ str         ┆ str     ┆ i64   ┆ i64        ┆   ┆ f64         ┆ i64        ┆ f64    ┆ ---         │
│             ┆         ┆       ┆            ┆   ┆             ┆            ┆        ┆ list[f64]   │
╞═════════════╪═════════╪═══════╪════════════╪═══╪═════════════╪════════════╪════════╪═════════════╡
│ Pregnancies ┆ Int64   ┆ 768   ┆ 0          ┆ … ┆ 0.0         ┆ 4          ┆ 0.9    ┆ [246.0,     │
│             ┆         ┆       ┆            ┆   ┆             ┆            ┆        ┆ 103.0, …    │
│             ┆         ┆       ┆            ┆   ┆             ┆            ┆        ┆ 1.0]        │
│ Glucose     ┆ Int64   ┆ 768   ┆ 0          ┆ … ┆ 0.0         ┆ 5          ┆ 0.173  ┆ [5.0, 0.0,  │
│             ┆         ┆       ┆            ┆   ┆             ┆            ┆        ┆ … 35.0]     │
│ BloodPressu ┆ Int64   ┆ 768   ┆ 0          ┆ … ┆ 0.0         ┆ 45         ┆ -1.84  ┆ [35.0, 0.0, │
│ re          ┆         ┆       ┆            ┆   ┆             ┆            ┆        ┆ … 2.0]      │
│ SkinThickne ┆ Int64   ┆ 768   ┆ 0          ┆ … ┆ 0.0         ┆ 1          ┆ 0.109  ┆ [231.0,     │
│ ss          ┆         ┆       ┆            ┆   ┆             ┆            ┆        ┆ 55.0, …     │
│             ┆         ┆       ┆            ┆   ┆             ┆            ┆        ┆ 1.0]        │
│ Insulin     ┆ Int64   ┆ 768   ┆ 0          ┆ … ┆ 0.0         ┆ 35         ┆ 2.268  ┆ [456.0,     │
│             ┆         ┆       ┆            ┆   ┆             ┆            ┆        ┆ 148.0, …    │
│             ┆         ┆       ┆            ┆   ┆             ┆            ┆        ┆ 1.0]        │
│ BMI         ┆ Float64 ┆ 768   ┆ 0          ┆ … ┆ 0.0         ┆ 19         ┆ -0.428 ┆ [11.0, 0.0, │
│             ┆         ┆       ┆            ┆   ┆             ┆            ┆        ┆ … 1.0]      │
│ DiabetesPed ┆ Float64 ┆ 768   ┆ 0          ┆ … ┆ 0.0         ┆ 29         ┆ 1.916  ┆ [266.0,     │
│ igreeFuncti ┆         ┆       ┆            ┆   ┆             ┆            ┆        ┆ 205.0, …    │
│ on          ┆         ┆       ┆            ┆   ┆             ┆            ┆        ┆ 3.0]        │
│ Age         ┆ Int64   ┆ 768   ┆ 0          ┆ … ┆ 0.0         ┆ 9          ┆ 1.127  ┆ [267.0,     │
│             ┆         ┆       ┆            ┆   ┆             ┆            ┆        ┆ 150.0, …    │
│             ┆         ┆       ┆            ┆   ┆             ┆            ┆        ┆ 1.0]        │
│ Outcome     ┆ Int64   ┆ 768   ┆ 0          ┆ … ┆ 0.0         ┆ 0          ┆ 0.634  ┆ [500.0,     │
│             ┆         ┆       ┆            ┆   ┆             ┆            ┆        ┆ 0.0, …      │
│             ┆         ┆       ┆            ┆   ┆             ┆            ┆        ┆ 268.0]      │

### 2.1 Analyze every column with `include='all'`

String columns get their own statistics: top value and frequency, and the
min / median / avg / max value length. Boolean columns are analyzed as 0/1
(Mean = share of True) and temporal columns report their earliest/latest timestamps.

In [4]:
ps.xray(df_titanic, include='all')

GT(_tbl_data=shape: (12, 22)
┌────────────┬─────────┬───────┬────────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ Column     ┆ Dtype   ┆ Count ┆ null_count ┆ … ┆ Median_Len ┆ Avg_Length ┆ Max_Length ┆ Distribut │
│ ---        ┆ ---     ┆ ---   ┆ ---        ┆   ┆ gth        ┆ ---        ┆ ---        ┆ ion_Plot  │
│ str        ┆ str     ┆ i64   ┆ i64        ┆   ┆ ---        ┆ f64        ┆ i64        ┆ ---       │
│            ┆         ┆       ┆            ┆   ┆ f64        ┆            ┆            ┆ list[f64] │
╞════════════╪═════════╪═══════╪════════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ PassengerI ┆ Int64   ┆ 156   ┆ 0          ┆ … ┆ null       ┆ null       ┆ null       ┆ [13.0,    │
│ d          ┆         ┆       ┆            ┆   ┆            ┆            ┆            ┆ 13.0, …   │
│            ┆         ┆       ┆            ┆   ┆            ┆            ┆            ┆ 13.0]     │
│ Survived   ┆ Int64   ┆ 156   ┆ 0          ┆ … ┆ null       ┆ null       ┆ null       ┆ [102.0,   │
│            ┆         ┆       ┆            ┆   ┆            ┆            ┆            ┆ 0.0, …    │
│            ┆         ┆       ┆            ┆   ┆            ┆            ┆            ┆ 54.0]     │
│ Pclass     ┆ Int64   ┆ 156   ┆ 0          ┆ … ┆ null       ┆ null       ┆ null       ┆ [30.0,    │
│            ┆         ┆       ┆            ┆   ┆            ┆            ┆            ┆ 0.0, …    │
│            ┆         ┆       ┆            ┆   ┆            ┆            ┆            ┆ 96.0]     │
│ Name       ┆ String  ┆ 156   ┆ 0          ┆ … ┆ 26.0       ┆ 27.2       ┆ 57         ┆ [1.0,     │
│            ┆         ┆       ┆            ┆   ┆            ┆            ┆            ┆ 1.0, …    │
│            ┆         ┆       ┆            ┆   ┆            ┆            ┆            ┆ 1.0]      │
│ Sex        ┆ String  ┆ 156   ┆ 0          ┆ … ┆ 4.0        ┆ 4.7        ┆ 6          ┆ [100.0,   │
│            ┆         ┆       ┆            ┆   ┆            ┆            ┆            ┆ 56.0]     │
│ …          ┆ …       ┆ …     ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …         │
│ Parch      ┆ Int64   ┆ 156   ┆ 0          ┆ … ┆ null       ┆ null       ┆ null       ┆ [121.0,   │
│            ┆         ┆       ┆            ┆   ┆            ┆            ┆            ┆ 0.0, …    │
│            ┆         ┆       ┆            ┆   ┆            ┆            ┆            ┆ 2.0]      │
│ Ticket     ┆ String  ┆ 156   ┆ 0          ┆ … ┆ 6.0        ┆ 7.0        ┆ 18         ┆ [2.0,     │
│            ┆         ┆       ┆            ┆   ┆            ┆            ┆            ┆ 2.0, …    │
│            ┆         ┆       ┆            ┆   ┆            ┆            ┆            ┆ 1.0]      │
│ Fare       ┆ Float64 ┆ 156   ┆ 0          ┆ … ┆ null       ┆ null       ┆ null       ┆ [113.0,   │
│            ┆         ┆       ┆            ┆   ┆            ┆            ┆            ┆ 18.0, …   │
│            ┆         ┆       ┆            ┆   ┆            ┆            ┆            ┆ 3.0]      │
│ Cabin      ┆ String  ┆ 31    ┆ 125        ┆ … ┆ 3.0        ┆ 3.9        ┆ 11         ┆ [2.0,     │
│            ┆         ┆       ┆            ┆   ┆            ┆            ┆            ┆ 2.0, …    │
│            ┆         ┆       ┆            ┆   ┆            ┆            ┆            ┆ 1.0]      │
│ Embarked   ┆ String  ┆ 155   ┆ 1          ┆ … ┆ 1.0        ┆ 1.0        ┆ 1          ┆ [110.0,   │
│            ┆         ┆       ┆            ┆   ┆            ┆            ┆            ┆ 32.0,     │
│            ┆         ┆       ┆            ┆   ┆            ┆            ┆            ┆ 13.0]     │

### 2.2 Expanded mode — everything

`expanded=True` adds quantiles, kurtosis/MAD, uniqueness and duplicate ratios,
normality/uniformity tests (scipy), optimal-dtype suggestions, and a per-column
**quality flag** that combines missingness, constancy, skew, outliers, and normality
into a single `✓ OK` / `⚠ SHAKY` verdict.

In [5]:
ps.xray(df_titanic, include='all', expanded=True)

GT(_tbl_data=shape: (12, 43)
┌─────────────┬─────────┬───────┬────────────┬───┬──────────┬────────┬──────────────┬──────────────┐
│ Column      ┆ Dtype   ┆ Count ┆ null_count ┆ … ┆ Earliest ┆ Latest ┆ Shakiness_Sc ┆ Quality_Flag │
│ ---         ┆ ---     ┆ ---   ┆ ---        ┆   ┆ ---      ┆ ---    ┆ ore          ┆ ---          │
│ str         ┆ str     ┆ i64   ┆ i64        ┆   ┆ null     ┆ null   ┆ ---          ┆ str          │
│             ┆         ┆       ┆            ┆   ┆          ┆        ┆ i64          ┆              │
╞═════════════╪═════════╪═══════╪════════════╪═══╪══════════╪════════╪══════════════╪══════════════╡
│ PassengerId ┆ Int64   ┆ 156   ┆ 0          ┆ … ┆ null     ┆ null   ┆ 2            ┆ ⚠ SHAKY      │
│ Survived    ┆ Int64   ┆ 156   ┆ 0          ┆ … ┆ null     ┆ null   ┆ 1            ┆ ✓ OK         │
│ Pclass      ┆ Int64   ┆ 156   ┆ 0          ┆ … ┆ null     ┆ null   ┆ 1            ┆ ✓ OK         │
│ Name        ┆ String  ┆ 156   ┆ 0          ┆ … ┆ null     ┆ null   ┆ 1            ┆ ✓ OK         │
│ Sex         ┆ String  ┆ 156   ┆ 0          ┆ … ┆ null     ┆ null   ┆ 0            ┆ ✓ OK         │
│ …           ┆ …       ┆ …     ┆ …          ┆ … ┆ …        ┆ …      ┆ …            ┆ …            │
│ Parch       ┆ Int64   ┆ 156   ┆ 0          ┆ … ┆ null     ┆ null   ┆ 4            ┆ ⚠ SHAKY      │
│ Ticket      ┆ String  ┆ 156   ┆ 0          ┆ … ┆ null     ┆ null   ┆ 0            ┆ ✓ OK         │
│ Fare        ┆ Float64 ┆ 156   ┆ 0          ┆ … ┆ null     ┆ null   ┆ 4            ┆ ⚠ SHAKY      │
│ Cabin       ┆ String  ┆ 31    ┆ 125        ┆ … ┆ null     ┆ null   ┆ 1            ┆ ✓ OK         │
│ Embarked    ┆ String  ┆ 155   ┆ 1          ┆ … ┆ null     ┆ null   ┆ 0            ┆ ✓ OK         │

### 2.3 String-heavy data

For String / Categorical / Enum columns the expanded view adds the **mode share**
(how dominant the top value is), the **top-3 values**, and a **sample** across the
frequency range — so mostly-text frames are first-class citizens too.

In [6]:
df_strings = pl.DataFrame({
    "city": ["Oslo", "Bergen", "Oslo", "Oslo", "Trondheim", "Bergen", "Oslo", "Stavanger"] * 25,
    "segment": pl.Series(["Private", "Business", "Private", "Public"] * 50, dtype=pl.Categorical),
    "revenue": [1200.5, 880.0, 1500.25, 990.0] * 50,
})
ps.xray(df_strings, include='all', expanded=True)

GT(_tbl_data=shape: (3, 43)
┌─────────┬────────────┬───────┬────────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ Column  ┆ Dtype      ┆ Count ┆ null_count ┆ … ┆ Normality_ ┆ Uniformity ┆ Shakiness_ ┆ Quality_F │
│ ---     ┆ ---        ┆ ---   ┆ ---        ┆   ┆ Test       ┆ _Test      ┆ Score      ┆ lag       │
│ str     ┆ str        ┆ i64   ┆ i64        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---       │
│         ┆            ┆       ┆            ┆   ┆ str        ┆ str        ┆ i64        ┆ str       │
╞═════════╪════════════╪═══════╪════════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ city    ┆ String     ┆ 200   ┆ 0          ┆ … ┆ N/A (non-n ┆ N/A (non-n ┆ 0          ┆ ✓ OK      │
│         ┆            ┆       ┆            ┆   ┆ umeric)    ┆ umeric)    ┆            ┆           │
│ segment ┆ Categorica ┆ 200   ┆ 0          ┆ … ┆ N/A (non-n ┆ N/A (non-n ┆ 0          ┆ ✓ OK      │
│         ┆ l          ┆       ┆            ┆   ┆ umeric)    ┆ umeric)    ┆            ┆           │
│ revenue ┆ Float64    ┆ 200   ┆ 0          ┆ … ┆ NON-NORMAL ┆ NON-UNIFOR ┆ 1          ┆ ✓ OK      │
│         ┆            ┆       ┆            ┆   ┆ (Shapiro-W ┆ M (KS,     ┆            ┆           │
│         ┆            ┆       ┆            ┆   ┆ ilk, p=0.… ┆ p=0.000)   ┆            ┆           │

### 2.4 Correlation with a target + model usability

- `corr_target=` adds a correlation column (with a ±1-scaled bar) against any numeric target.
- `model_usability=True` scores each column 0–100 for ML readiness with flags
  (ID-like, constant, extreme outliers/skew, high missingness, …) and a plain-text recommendation.

In [7]:
ps.xray(df_diabetes, corr_target='Outcome', model_usability=True)

GT(_tbl_data=shape: (9, 21)
┌────────────┬─────────┬───────┬────────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ Column     ┆ Dtype   ┆ Count ┆ null_count ┆ … ┆ Correlatio ┆ Usability_ ┆ Usability_ ┆ Recommend │
│ ---        ┆ ---     ┆ ---   ┆ ---        ┆   ┆ n_Plot     ┆ Flags      ┆ Score      ┆ ation     │
│ str        ┆ str     ┆ i64   ┆ i64        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---       │
│            ┆         ┆       ┆            ┆   ┆ f64        ┆ str        ┆ f64        ┆ str       │
╞════════════╪═════════╪═══════╪════════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ Pregnancie ┆ Int64   ┆ 768   ┆ 0          ┆ … ┆ 0.222      ┆ -          ┆ 100.0      ┆ Good for  │
│ s          ┆         ┆       ┆            ┆   ┆            ┆            ┆            ┆ modeling  │
│ Glucose    ┆ Int64   ┆ 768   ┆ 0          ┆ … ┆ 0.467      ┆ -          ┆ 100.0      ┆ Good for  │
│            ┆         ┆       ┆            ┆   ┆            ┆            ┆            ┆ modeling  │
│ BloodPress ┆ Int64   ┆ 768   ┆ 0          ┆ … ┆ 0.065      ┆ -          ┆ 100.0      ┆ Good for  │
│ ure        ┆         ┆       ┆            ┆   ┆            ┆            ┆            ┆ modeling  │
│ SkinThickn ┆ Int64   ┆ 768   ┆ 0          ┆ … ┆ 0.075      ┆ -          ┆ 100.0      ┆ Good for  │
│ ess        ┆         ┆       ┆            ┆   ┆            ┆            ┆            ┆ modeling  │
│ Insulin    ┆ Int64   ┆ 768   ┆ 0          ┆ … ┆ 0.131      ┆ -          ┆ 100.0      ┆ Good for  │
│            ┆         ┆       ┆            ┆   ┆            ┆            ┆            ┆ modeling  │
│ BMI        ┆ Float64 ┆ 768   ┆ 0          ┆ … ┆ 0.293      ┆ -          ┆ 100.0      ┆ Good for  │
│            ┆         ┆       ┆            ┆   ┆            ┆            ┆            ┆ modeling  │
│ DiabetesPe ┆ Float64 ┆ 768   ┆ 0          ┆ … ┆ 0.174      ┆ -          ┆ 100.0      ┆ Good for  │
│ digreeFunc ┆         ┆       ┆            ┆   ┆            ┆            ┆            ┆ modeling  │
│ tion       ┆         ┆       ┆            ┆   ┆            ┆            ┆            ┆           │
│ Age        ┆ Int64   ┆ 768   ┆ 0          ┆ … ┆ 0.238      ┆ -          ┆ 100.0      ┆ Good for  │
│            ┆         ┆       ┆            ┆   ┆            ┆            ┆            ┆ modeling  │
│ Outcome    ┆ Int64   ┆ 768   ┆ 0          ┆ … ┆ null       ┆ BN         ┆ 96.610169  ┆ Good for  │
│            ┆         ┆       ┆            ┆   ┆            ┆            ┆            ┆ modeling  │

### 2.5 Big data? No problem

The whole X-ray of the 70,000-row cardio dataset takes well under a second —
the header of every table shows the exact timing.

In [8]:
ps.xray(df_cardio, include='all', expanded=True)

GT(_tbl_data=shape: (13, 43)
┌────────┬─────────┬───────┬────────────┬───┬──────────┬────────┬─────────────────┬──────────────┐
│ Column ┆ Dtype   ┆ Count ┆ null_count ┆ … ┆ Earliest ┆ Latest ┆ Shakiness_Score ┆ Quality_Flag │
│ ---    ┆ ---     ┆ ---   ┆ ---        ┆   ┆ ---      ┆ ---    ┆ ---             ┆ ---          │
│ str    ┆ str     ┆ i64   ┆ i64        ┆   ┆ null     ┆ null   ┆ i64             ┆ str          │
╞════════╪═════════╪═══════╪════════════╪═══╪══════════╪════════╪═════════════════╪══════════════╡
│ id     ┆ Int64   ┆ 70000 ┆ 0          ┆ … ┆ null     ┆ null   ┆ 2               ┆ ⚠ SHAKY      │
│ age    ┆ Int64   ┆ 70000 ┆ 0          ┆ … ┆ null     ┆ null   ┆ 1               ┆ ✓ OK         │
│ gender ┆ Int64   ┆ 70000 ┆ 0          ┆ … ┆ null     ┆ null   ┆ 2               ┆ ⚠ SHAKY      │
│ height ┆ Int64   ┆ 70000 ┆ 0          ┆ … ┆ null     ┆ null   ┆ 2               ┆ ⚠ SHAKY      │
│ weight ┆ Float64 ┆ 70000 ┆ 0          ┆ … ┆ null     ┆ null   ┆ 1               ┆ ✓ OK         │
│ …      ┆ …       ┆ …     ┆ …          ┆ … ┆ …        ┆ …      ┆ …               ┆ …            │
│ gluc   ┆ Int64   ┆ 70000 ┆ 0          ┆ … ┆ null     ┆ null   ┆ 4               ┆ ⚠ SHAKY      │
│ smoke  ┆ Int64   ┆ 70000 ┆ 0          ┆ … ┆ null     ┆ null   ┆ 4               ┆ ⚠ SHAKY      │
│ alco   ┆ Int64   ┆ 70000 ┆ 0          ┆ … ┆ null     ┆ null   ┆ 5               ┆ ⚠ SHAKY      │
│ active ┆ Int64   ┆ 70000 ┆ 0          ┆ … ┆ null     ┆ null   ┆ 3               ┆ ⚠ SHAKY      │
│ cardio ┆ Int64   ┆ 70000 ┆ 0          ┆ … ┆ null     ┆ null   ┆ 2               ┆ ⚠ SHAKY      │

### 2.6 Plain DataFrame output

Set `great_tables=False` to get the summary as a regular Polars DataFrame —
useful for programmatic checks or piping into your own reports.

In [ ]:
summary = ps.xray(df_diabetes, great_tables=False)
summary.select(["column", "mean", "std", "pct_missing", "n_outliers", "skew"])

---
## 3 | `ps.fix()` — clean & optimize in one call

`fix()` runs the safe, **lossless** cleanups by default and prints a report:

| Step | Default | What it does |
|---|---|---|
| `case="snake"` | on | Clean column names (`"Kunde Navn"` → `kunde_navn`); also `camel`, `pascal`, `kebab`, `upper`, `lower`, or `None` |
| `strip_strings` | on | Trim whitespace; empty/whitespace-only strings → null |
| `shrink_dtypes` | on | Downcast ints/floats, low-cardinality strings → Categorical |
| `drop_empty_columns` | on | Remove 100%-null columns |
| `drop_duplicate_rows` | **off** | Remove exact duplicate rows |
| `missing_threshold` | **off** | Drop columns above a missing-share threshold |
| `drop_constant_columns` | **off** | Drop single-value columns |
| `outliers` | **off** | Null out extreme values (`"iqr"` / `"zscore"`) |

Anything that removes or alters data is opt-in. The input frame is never mutated.

In [10]:
df_messy = pl.DataFrame({
    "Kunde Navn": ["  Alice ", "Bob", "", "Bob", None],
    "Årlig Inntekt (kr)": [50_000, 60_000, 55_000, 60_000, None],
    "myColumnName": [1.0, 2.0, 3.0, 2.0, 1.0],
    "empty_col": pl.Series([None] * 5, dtype=pl.String),
    "const": ["x", "x", "x", "x", "x"],
})
df_messy

shape: (5, 5)
┌────────────┬────────────────────┬──────────────┬───────────┬───────┐
│ Kunde Navn ┆ Årlig Inntekt (kr) ┆ myColumnName ┆ empty_col ┆ const │
│ ---        ┆ ---                ┆ ---          ┆ ---       ┆ ---   │
│ str        ┆ i64                ┆ f64          ┆ str       ┆ str   │
╞════════════╪════════════════════╪══════════════╪═══════════╪═══════╡
│   Alice    ┆ 50000              ┆ 1.0          ┆ null      ┆ x     │
│ Bob        ┆ 60000              ┆ 2.0          ┆ null      ┆ x     │
│            ┆ 55000              ┆ 3.0          ┆ null      ┆ x     │
│ Bob        ┆ 60000              ┆ 2.0          ┆ null      ┆ x     │
│ null       ┆ null               ┆ 1.0          ┆ null      ┆ x     │
└────────────┴────────────────────┴──────────────┴───────────┴───────┘

In [11]:
df_fixed = ps.fix(df_messy)
df_fixed

ps.fix report
─────────────
Renamed 3 column(s) to snake case
Stripped whitespace in 3 string column(s); 1 value(s) trimmed, 1 empty string(s) -> null
Dropped 1 empty column(s): empty_col
Shrunk dtypes in 4 column(s): kunde_navn: String -> Categorical; arlig_inntekt_kr: Int64 -> UInt16; my_column_name: Float64 -> Float32; const: String -> Categorical
Memory: 0.1 KB -> 0.1 KB (28% saved)
Rows: 5 (unchanged) | Columns: 5 -> 4

shape: (5, 4)
┌────────────┬──────────────────┬────────────────┬───────┐
│ kunde_navn ┆ arlig_inntekt_kr ┆ my_column_name ┆ const │
│ ---        ┆ ---              ┆ ---            ┆ ---   │
│ cat        ┆ u16              ┆ f32            ┆ cat   │
╞════════════╪══════════════════╪════════════════╪═══════╡
│ Alice      ┆ 50000            ┆ 1.0            ┆ x     │
│ Bob        ┆ 60000            ┆ 2.0            ┆ x     │
│ null       ┆ 55000            ┆ 3.0            ┆ x     │
│ Bob        ┆ 60000            ┆ 2.0            ┆ x     │
│ null       ┆ null             ┆ 1.0            ┆ x     │
└────────────┴──────────────────┴────────────────┴───────┘

### 3.1 Pick your naming style with `case=`

In [12]:
for style in ["snake", "camel", "pascal", "kebab", "upper", "lower"]:
    cols = ps.fix(df_messy, case=style, verbose=False).columns
    print(f"{style:7s} -> {cols}")

snake   -> ['kunde_navn', 'arlig_inntekt_kr', 'my_column_name', 'const']
camel   -> ['kundeNavn', 'arligInntektKr', 'myColumnName', 'const']
pascal  -> ['KundeNavn', 'ArligInntektKr', 'MyColumnName', 'Const']
kebab   -> ['kunde-navn', 'arlig-inntekt-kr', 'my-column-name', 'const']
upper   -> ['KUNDE_NAVN', 'ARLIG_INNTEKT_KR', 'MYCOLUMNNAME', 'CONST']
lower   -> ['kunde_navn', 'arlig_inntekt_kr', 'mycolumnname', 'const']

### 3.2 Opt in to deeper cleaning

In [13]:
ps.fix(
    df_messy,
    drop_duplicate_rows=True,     # exact duplicates out
    drop_constant_columns=True,   # single-value columns out
    missing_threshold=0.3,        # drop columns >30% missing
)

ps.fix report
─────────────
Renamed 3 column(s) to snake case
Stripped whitespace in 3 string column(s); 1 value(s) trimmed, 1 empty string(s) -> null
Dropped 1 empty column(s): empty_col
Dropped 1 column(s) >30% missing: kunde_navn
Dropped 1 constant column(s): const
Removed 1 duplicate row(s)
Shrunk dtypes in 2 column(s): arlig_inntekt_kr: Int64 -> UInt16; my_column_name: Float64 -> Float32
Memory: 0.1 KB -> 0.0 KB (75% saved)
Rows: 5 -> 4 | Columns: 5 -> 2

shape: (4, 2)
┌──────────────────┬────────────────┐
│ arlig_inntekt_kr ┆ my_column_name │
│ ---              ┆ ---            │
│ u16              ┆ f32            │
╞══════════════════╪════════════════╡
│ 50000            ┆ 1.0            │
│ 60000            ┆ 2.0            │
│ 55000            ┆ 3.0            │
│ null             ┆ 1.0            │
└──────────────────┴────────────────┘

### 3.3 On real data: titanic shrinks ~40% with pure defaults

In [14]:
df_clean = ps.fix(df_titanic)
df_clean.head(5)

ps.fix report
─────────────
Renamed 12 column(s) to snake case
Stripped whitespace in 5 string column(s); 1 value(s) trimmed, 0 empty string(s) -> null
Shrunk dtypes in 8 column(s): passenger_id: Int64 -> UInt8; survived: Int64 -> UInt8; pclass: Int64 -> UInt8; sex: String -> Categorical; age: Float64 -> Float32; sib_sp: Int64 -> UInt8; parch: Int64 -> UInt8; embarked: String -> Categorical
Memory: 14.7 KB -> 9.2 KB (38% saved)
Rows: 156 (unchanged) | Columns: 12 (unchanged)

shape: (5, 12)
┌──────────────┬──────────┬────────┬──────────────────┬───┬───────────┬─────────┬───────┬──────────┐
│ passenger_id ┆ survived ┆ pclass ┆ name             ┆ … ┆ ticket    ┆ fare    ┆ cabin ┆ embarked │
│ ---          ┆ ---      ┆ ---    ┆ ---              ┆   ┆ ---       ┆ ---     ┆ ---   ┆ ---      │
│ u8           ┆ u8       ┆ u8     ┆ str              ┆   ┆ str       ┆ f64     ┆ str   ┆ cat      │
╞══════════════╪══════════╪════════╪══════════════════╪═══╪═══════════╪═════════╪═══════╪══════════╡
│ 1            ┆ 0        ┆ 3      ┆ Braund, Mr. Owen ┆ … ┆ A/5 21171 ┆ 7.25    ┆ null  ┆ S        │
│              ┆          ┆        ┆ Harris           ┆   ┆           ┆         ┆       ┆          │
│ 2            ┆ 1        ┆ 1      ┆ Cumings, Mrs.    ┆ … ┆ PC 17599  ┆ 71.2833 ┆ C85   ┆ C        │
│              ┆          ┆        ┆ John Bradley     ┆   ┆           ┆         ┆       ┆          │
│              ┆          ┆        ┆ (Fl…             ┆   ┆           ┆         ┆       ┆          │
│ 3            ┆ 1        ┆ 3      ┆ Heikkinen, Miss. ┆ … ┆ STON/O2.  ┆ 7.925   ┆ null  ┆ S        │
│              ┆          ┆        ┆ Laina            ┆   ┆ 3101282   ┆         ┆       ┆          │
│ 4            ┆ 1        ┆ 1      ┆ Futrelle, Mrs.   ┆ … ┆ 113803    ┆ 53.1    ┆ C123  ┆ S        │
│              ┆          ┆        ┆ Jacques Heath (… ┆   ┆           ┆         ┆       ┆          │
│ 5            ┆ 0        ┆ 3      ┆ Allen, Mr.       ┆ … ┆ 373450    ┆ 8.05    ┆ null  ┆ S        │
│              ┆          ┆        ┆ William Henry    ┆   ┆           ┆         ┆       ┆          │
└──────────────┴──────────┴────────┴──────────────────┴───┴───────────┴─────────┴───────┴──────────┘

---
## 4 | Plots

All plotting functions accept `backend="plotly"` (interactive, default) or `backend="altair"`.

### 4.1 Correlation heatmap — full matrix or against a target

In [15]:
ps.corr_heatmap(df_diabetes)

In [16]:
ps.corr_heatmap(df_diabetes, target='Outcome')

### 4.2 Missing values per column

In [17]:
ps.missingval_plot(df_titanic, normalize=True)

### 4.3 Distribution of a single column

In [18]:
ps.dist_plot(df_diabetes, column='Glucose', bins=40)

### 4.4 Categorical frequencies — top and bottom categories

In [19]:
ps.cat_plot(df_titanic, top=5, bottom=3)

### 4.5 Clustered correlation plot (requires scipy)

In [20]:
ps.corr_plot(df_diabetes, clustered=True, method='spearman')

---
## 5 | The 3-line EDA workflow

Load → fix → xray. That's the whole pipeline for a first look at any dataset.

In [21]:
df = ps.cardio()                                   # 1. load (or pl.read_csv/parquet)
df = ps.fix(df)                                    # 2. clean + optimize
ps.xray(df, include='all', corr_target='cardio')   # 3. inspect

ps.fix report
─────────────
Shrunk dtypes in 12 column(s): id: Int64 -> UInt32; age: Int64 -> UInt16; gender: Int64 -> UInt8; height: Int64 -> UInt8; ap_hi: Int64 -> Int16; ap_lo: Int64 -> Int16; cholesterol: Int64 -> UInt8; gluc: Int64 -> UInt8; smoke: Int64 -> UInt8; alco: Int64 -> UInt8; active: Int64 -> UInt8; cardio: Int64 -> UInt8
Memory: 6.9 MB -> 1.7 MB (75% saved)
Rows: 70,000 (unchanged) | Columns: 13 (unchanged)

GT(_tbl_data=shape: (13, 18)
┌────────┬─────────┬───────┬────────────┬───┬────────┬───────────────┬─────────────┬───────────────┐
│ Column ┆ Dtype   ┆ Count ┆ null_count ┆ … ┆ skew   ┆ Distribution_ ┆ Correlation ┆ Correlation_P │
│ ---    ┆ ---     ┆ ---   ┆ ---        ┆   ┆ ---    ┆ Plot          ┆ ---         ┆ lot           │
│ str    ┆ str     ┆ i64   ┆ i64        ┆   ┆ f64    ┆ ---           ┆ str         ┆ ---           │
│        ┆         ┆       ┆            ┆   ┆        ┆ list[f64]     ┆             ┆ f64           │
╞════════╪═════════╪═══════╪════════════╪═══╪════════╪═══════════════╪═════════════╪═══════════════╡
│ id     ┆ UInt32  ┆ 70000 ┆ 0          ┆ … ┆ -0.001 ┆ [5874.0,      ┆ 0.004       ┆ 0.004         │
│        ┆         ┆       ┆            ┆   ┆        ┆ 5791.0, …     ┆             ┆               │
│        ┆         ┆       ┆            ┆   ┆        ┆ 5774.0]       ┆             ┆               │
│ age    ┆ UInt16  ┆ 70000 ┆ 0          ┆ … ┆ -0.307 ┆ [4.0, 0.0, …  ┆ 0.238       ┆ 0.238         │
│        ┆         ┆       ┆            ┆   ┆        ┆ 7042.0]       ┆             ┆               │
│ gender ┆ UInt8   ┆ 70000 ┆ 0          ┆ … ┆ 0.631  ┆ [45530.0,     ┆ 0.008       ┆ 0.008         │
│        ┆         ┆       ┆            ┆   ┆        ┆ 0.0, …        ┆             ┆               │
│        ┆         ┆       ┆            ┆   ┆        ┆ 24470.0]      ┆             ┆               │
│ height ┆ UInt8   ┆ 70000 ┆ 0          ┆ … ┆ -0.642 ┆ [17.0, 7.0, … ┆ -0.011      ┆ -0.011        │
│        ┆         ┆       ┆            ┆   ┆        ┆ 1.0]          ┆             ┆               │
│ weight ┆ Float64 ┆ 70000 ┆ 0          ┆ … ┆ 1.012  ┆ [5.0, 126.0,  ┆ 0.182       ┆ 0.182         │
│        ┆         ┆       ┆            ┆   ┆        ┆ … 2.0]        ┆             ┆               │
│ …      ┆ …       ┆ …     ┆ …          ┆ … ┆ …      ┆ …             ┆ …           ┆ …             │
│ gluc   ┆ UInt8   ┆ 70000 ┆ 0          ┆ … ┆ 2.397  ┆ [59479.0,     ┆ 0.089       ┆ 0.089         │
│        ┆         ┆       ┆            ┆   ┆        ┆ 0.0, …        ┆             ┆               │
│        ┆         ┆       ┆            ┆   ┆        ┆ 5331.0]       ┆             ┆               │
│ smoke  ┆ UInt8   ┆ 70000 ┆ 0          ┆ … ┆ 2.906  ┆ [63831.0,     ┆ -0.015      ┆ -0.015        │
│        ┆         ┆       ┆            ┆   ┆        ┆ 0.0, …        ┆             ┆               │
│        ┆         ┆       ┆            ┆   ┆        ┆ 6169.0]       ┆             ┆               │
│ alco   ┆ UInt8   ┆ 70000 ┆ 0          ┆ … ┆ 3.957  ┆ [66236.0,     ┆ -0.007      ┆ -0.007        │
│        ┆         ┆       ┆            ┆   ┆        ┆ 0.0, …        ┆             ┆               │
│        ┆         ┆       ┆            ┆   ┆        ┆ 3764.0]       ┆             ┆               │
│ active ┆ UInt8   ┆ 70000 ┆ 0          ┆ … ┆ -1.529 ┆ [13739.0,     ┆ -0.036      ┆ -0.036        │
│        ┆         ┆       ┆            ┆   ┆        ┆ 0.0, …        ┆             ┆               │
│        ┆         ┆       ┆            ┆   ┆        ┆ 56261.0]      ┆             ┆               │
│ cardio ┆ UInt8   ┆ 70000 ┆ 0          ┆ … ┆ 0.001  ┆ [35021.0,     ┆ -           ┆ null          │
│        ┆         ┆       ┆            ┆   ┆        ┆ 0.0, …        ┆             ┆               │
│        ┆         ┆       ┆            ┆   ┆        ┆ 34979.0]      ┆             ┆               │

---
## Learn more

- **Install**: `pip install polarscope` — [PyPI](https://pypi.org/project/polarscope/)
- **Source & issues**: [github.com/pytoned/polarscope](https://github.com/pytoned/polarscope)
- **Docs in your editor**: every function has a full docstring — try `help(ps.xray)`

*Built on [Polars](https://pola.rs) and [Great Tables](https://posit-dev.github.io/great-tables/). Inspired by [klib](https://github.com/akanz1/klib).*